youtube_analytics_capstone:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      host: "{{ env_var('SNOWFLAKE_HOST') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      schema: "{{ env_var('STUDENT_SCHEMA') }}"
      threads: 4
      client_session_keep_alive: false
      query_tag: youtube_capstone_dbt

     